### ISSUE TITLE
[1.16] Mod incorrectly unifies ores within the same mod

### ISSUE THREAD

**Issue by CactusDuud** [Meldexun/UnifiedResources#4]
This is sort of an edge case, but with mods that add multiple variants of ore such as [Emendatus Enigmatica](https://www.curseforge.com/minecraft/mc-mods/emendatus-enigmatica), ores are unified to andesite ore instead of stone.

The default ore within the mod has the id emendatusenigmatica:x_ore but for some reason this isn't prioritised over emendatusenigmatica:x_ore_andesite.

**Comment by Meldexun** [comment]
This is not a bug.
There is no "default ore". Items/Blocks can be added to tags but these tags don't have any order.
Maybe I can add some sort of item priority config option in the future but that is very low priority.
